FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.22 AS builder
WORKDIR /go/src/github.com/openshift/osd-example-operator/
COPY . .
RUN  CGO_ENABLED=0 GOFLAGS="-mod=mod" go test ./osde2e -v -c --tags=osde2e -o /harness.test

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest
COPY --from=builder ./harness.test harness.test
ENTRYPOINT [ "/harness.test" ]
