apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform"]'
  name: osd-example-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Example is the Schema for the Examples API
      displayName: Example
      kind: Example
      name: examples.managed.openshift.io
      version: v1alpha1
  description: An example operator based on the Managed OpenShift operators used to
    develop CICD strategies
  displayName: OSD Example Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - test
  - cicd
  - example
  - operator-sdk
  - golang
  - osde2e
  - node
  - openshift-dedicated
  - openshift
  - redhat
  links:
  - name: Osd Example Operator
    url: https://osd-example-operator.domain
  maintainers:
  - email: example
    name: example
  maturity: alpha
  provider:
    name: redhat
  version: 0.0.0
