apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "managed.openshift.io/v1alpha1"
          "kind": "Example",
          "metadata": {
            "name": "example"
          }
        }
      ]
    capabilities: Basic Install
    categories: A list of comma separated categories that your operator falls under.
    certified: "false"
    description: Example operator e2e test harness
    containerImage: quay.io/app-sre/osd-example-operator:latest
    support: osde2e
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform"]'
  name: osd-example-operator.v0.0.0
  namespace: openshift-osd-example-operator
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Example is the Schema for the Examples API
      displayName: Example
      kind: Example
      name: examples.managed.openshift.io
      version: v1alpha1
  description: example operator
  displayName: osd-example-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - managed-openshift
  - operator-sdk
  - golang
  - osde2e
  - node
  - openshift-dedicated
  - openshift
  - redhat
  links:
  - name: OSD Example Operator
    url: https://github.com/openshift/osd-example-operator
  maintainers:
  - email: test
    name: test
  maturity: alpha
  provider:
    name: redhat
  version: 0.0.0
