kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-example-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
