---
apiVersion: v1
kind: Secret
metadata:
  name: osde2e-credentials
  namespace: argo
  labels:
    app: osde2e-workflow
    component: credentials
type: Opaque
stringData:
  # OCM Credentials (get from vault: sdcicd_aws/)
  ocm-client-id: "your-ocm-client-id"                   # Copy from vault: ocm/ocm-client-id
  ocm-client-secret: "your-ocm-client-secret"           # Copy from vault: ocm/ocm-client-secret

  # AWS Credentials (get from vault: sdcicd_aws/)
  aws-access-key-id: "your-aws-access-key-id"           # From vault: sdcicd_aws/access-key-id
  aws-secret-access-key: "your-aws-secret-access-key"   # From vault: sdcicd_aws/secret-access-key
  aws-account-id: "your-aws-account-id"                 # From vault: sdcicd_aws/aws-account-id
  cloud-provider-region: "us-east-1"                    # AWS region for your cluster

  # Slack Notification (optional)
  slack-webhook-url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"