---
apiVersion: v1
kind: Secret
metadata:
  name: osde2e-credentials
  namespace: argo
  labels:
    app: osde2e-gate
    component: credentials
type: Opaque
stringData:
  # OCM Credentials
  ocm-cluster-id: # Copy from vault: sdcicd_aws/ocm-cluster-id
  ocm-client-id: "ocm-sd-cicada"
  ocm-client-secret:  # Copy from vault: sdcicd_aws/ocm-client-secret

  # AWS Credentials
  aws-access-key-id: # Copy from vault: sdcicd_aws/access-key-id
  aws-secret-access-key:  # Copy from vault: sdcicd_aws/secret-access-key
  aws-account-id: # Copy from vault: sdcicd_aws/aws-account-id

  # Test Configuration
  cloud-provider-region: "us-east-1"
  ad-hoc-test-images: "https://quay.io/repository/rh_ee_yiqzhang/splunk-forwarder-operator-e2e"
  skip-destroy-cluster: "true"
  osde2e-configs: "rosa,sts,int,ad-hoc-image"

  # Slack Notification
  slack-webhook-url: "https://hooks.slack.com/services/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"

---
# ConfigMap for OSDE2E configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: osde2e-config
  namespace: argo
  labels:
    app: osde2e-gate
    component: config
data:
  osde2e-config.yaml: |
    cluster:
      useExisting: true
      id: "2kjhcu00tne378o2lkcb1pbqt7gqmf7p"
      skipCreation: true
      skipDestroy: true
      kubeconfig: "/tmp/kubeconfig/config"
    tests:
      skipMustGather: true
      skipDestroyCluster: true
      skipHealthCheck: false
      useExistingCluster: true
    ocm:
      env: "int"
      clusterId: "2kjhcu00tne378o2lkcb1pbqt7gqmf7p"
    aws:
      region: "us-east-1"
      accountId: "Copy from vault"
