apiVersion: v1
kind: ConfigMap
metadata:
  name: osde2e-stage-config
  namespace: argo
data:
  stage-config.yaml: |
    # OSDE2E Configuration for STAGE Environment
    cluster:
      name: "stage-cluster"
      version: "4.14"
      region: "us-west-2"

    tests:
      testTimeout: 7200  # 2 hour timeout for stage
      pollingTimeout: 900  # 15 minutes polling timeout
      maxRetries: 2
      parallelism: 4

    operator:
      name: "osd-example-operator"
      namespace: "osd-example-operator-stage"

    # Test configuration - this will be overridden by environment variables
    testHarnesses:
      - "${OPERATOR_IMAGE}:${IMAGE_TAG}"

    # More comprehensive tests for stage
    skipTests: []

    # Environment specific settings
    environment:
      type: "staging"
      clusterProvider: "aws"
      managed: true

    # Additional stage validations
    validations:
      - "operator-metrics"
      - "performance-baseline"