apiVersion: v1
kind: ConfigMap
metadata:
  name: osde2e-int-config
  namespace: argo-workflows
data:
  int-config.yaml: |
    # OSDE2E Configuration for INT Environment
    cluster:
      name: "int-cluster"
      version: "4.14"
      region: "us-east-1"

    tests:
      testTimeout: 3600  # 1 hour timeout
      pollingTimeout: 600  # 10 minutes polling timeout
      maxRetries: 3
      parallelism: 2

    operator:
      name: "osd-example-operator"
      namespace: "osd-example-operator-int"

    # Test configuration - this will be overridden by environment variables
    testHarnesses:
      - "${OPERATOR_IMAGE}:${IMAGE_TAG}"

    # Skip tests that are not relevant for INT
    skipTests:
      - "install-cleanup"
      - "uninstall"

    # Environment specific settings
    environment:
      type: "integration"
      clusterProvider: "aws"
      managed: true