apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: osd-example-operator-0.0.1
  namespace: placeholder
  annotations:
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform"]'
    categories: A list of comma separated categories that your operator falls under.
    certified: "false"
    description: Operator used for CI testing and development
    containerImage: quay.io/app-sre/osd-example-operator:GENERATED
    support: Red Hat OpenShift SRE
spec:
  displayName: osd-example-operator
  description: Operator used for CI testing and development
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  version: 0.0.1
  provider:
    name: Red Hat, Inc
  maturity: alpha
  maintainers:
  - name: OpenShift SRE
  links:
  - url: https://github.com/openshift/osd-example-operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: osd-example-operator
        # Rules will be added here by the generate-operator-bundle.py script.
      deployments:
      - name: osd-example-operator
        # Deployment spec will be added here by the generate-operator-bundle.py script.
  customresourcedefinitions:
    owned:
    # CRD's will be added here by the generate-operator-bundle.py
